# Named Aggregation in Pandas
####  in pandas, named aggregation is a clean syntax used inside .groupby().agg() that allows you to calculate multiple summary statistics across different columns while explicitly naming the output columns at the same time. This prevents pandas from generating messy multi-index columns.

# ----------------------------------------------------
# df.groupby('group_column').agg(
#   new_column_name=('target_column', 'agg_func')
# )
# ----------------------------------------------------

In [2]:
import pandas as pd

In [3]:
car_stocks = pd.read_csv('../../../data/car_stocks.csv')

In [4]:
car_stocks.head()

,Symbol,Date,Open,High,Low,Close,Adj Close,Volume
0,RIVN,2021-11-10,106.750000,119.459999,95.199997,100.730003,100.730003,103679500
1,RIVN,2021-11-11,114.625000,125.000000,108.010002,122.989998,122.989998,83668200
2,RIVN,2021-11-12,128.645004,135.199997,125.250000,129.949997,129.949997,50437500
3,RIVN,2021-11-15,130.800003,152.529999,127.510002,149.360001,149.360001,64982300
4,RIVN,2021-11-16,163.800003,179.470001,153.779999,172.009995,172.009995,94036600

#### We want to find the MIN-Open and MAX-Open and MIN-Close and MAX-Close price

In [5]:
symbol_group = car_stocks.groupby('Symbol')

#### Here we will use the normal method of aggregation using a dictionary

In [6]:
symbol_group.agg({'Open' : ['min', 'max'], 'Close' : ['min', 'max']})

              Open                   Close
               min         max         min         max
Symbol
GM       57.849998   64.330002   59.270000   64.610001
LCID     42.299999   56.200001   40.750000   55.520000
RIVN    106.750000  163.800003  100.730003  172.009995

## Now we will use NAMED AGGREGATION

In [10]:
symbol_group.agg(
    min_open = ('Open', 'min' ),
    max_open = ('Open', 'max' ),
    min_close = ('Close', 'min'),
    max_close = ('Close', 'max')
)

          min_open    max_open   min_close   max_close
Symbol
GM       57.849998   64.330002   59.270000   64.610001
LCID     42.299999   56.200001   40.750000   55.520000
RIVN    106.750000  163.800003  100.730003  172.009995