# Modifying Dataframes

## 1. Dropping Columns

In [1]:
import pandas as pd

btc = pd.read_csv('../data/coin_Bitcoin.csv')
btc.head()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.0,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.0,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.0,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.0,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.0,1.085995e+09

##### Since the columns Symbol and Name are not of any help so we will drop them
##### The axis = 1 is for specifying column. axis = 0 is for rows
##### We can also specify by axis = 'columns'
##### This will not change the original dataset. For modifying the original dataset we need (inplace = True)

In [2]:
btc_modified = btc.drop(labels='Name', axis=1)

In [5]:
btc_modified.head()

,SNo,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.0,1.603769e+09
1,2,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.0,1.542813e+09
2,3,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.0,1.298955e+09
3,4,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.0,1.168517e+09
4,5,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.0,1.085995e+09

##### Now we will drop the Symbol column and we will make changes to the original source this time using (inplace = True)

In [6]:
btc.drop(labels='Symbol', axis=1, inplace=True)

In [8]:
btc.head()

,SNo,Name,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.0,1.603769e+09
1,2,Bitcoin,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.0,1.542813e+09
2,3,Bitcoin,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.0,1.298955e+09
3,4,Bitcoin,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.0,1.168517e+09
4,5,Bitcoin,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.0,1.085995e+09

#### Multi-Column Drop

In [16]:
btc.drop(labels=['SNo', 'Name', 'Volume'], axis=1).head()

,Date,High,Low,Open,Close,Marketcap
0,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,1.603769e+09
1,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,1.542813e+09
2,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,1.298955e+09
3,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,1.168517e+09
4,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,1.085995e+09

##### Another way of Multi-column delete is by using (columns = [ ])

In [17]:
btc.drop(columns=['SNo', 'Name', 'Volume']).head()

,Date,High,Low,Open,Close,Marketcap
0,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,1.603769e+09
1,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,1.542813e+09
2,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,1.298955e+09
3,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,1.168517e+09
4,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,1.085995e+09

#### Another method involves no column deletion instead do selective selection of columns

In [15]:
btc[['Date', 'High', 'Low']].head()

                  Date        High         Low
0  2013-04-29 23:59:59  147.488007  134.000000
1  2013-04-30 23:59:59  146.929993  134.050003
2  2013-05-01 23:59:59  139.889999  107.720001
3  2013-05-02 23:59:59  125.599998   92.281898
4  2013-05-03 23:59:59  108.127998   79.099998