# Multi-Indexing loc[ ]

In [54]:
import pandas as pd

In [55]:
titanic = pd.read_csv('../../../data/titanic.csv')
state_pops = pd.read_csv('../../../data/state_pops.csv')

In [56]:
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

##### For example I want to access the row at 7th Index position

In [57]:
titanic.loc[7]

pclass                            1
survived                          0
name         Andrews, Mr. Thomas Jr
sex                            male
age                              39
sibsp                             0
parch                             0
ticket                       112050
fare                              0
cabin                           A36
embarked                          S
boat                              ?
body                              ?
home.dest               Belfast, NI
Name: 7, dtype: object

##### We can also access the entire dta frame for the 7th index position

In [58]:
titanic.loc[[7]]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"

#### We can also search a word in a dataframe as well

In [59]:
state_pops.head()

  state  year  population
0    AL  2012   4817528.0
1    AL  2010   4785570.0
2    AL  2011   4801627.0
3    AL  2009   4757938.0
4    AL  2013   4833722.0

In [60]:
state_pops.set_index(['state', 'year'], inplace=True)

In [61]:
state_pops

             population
state year
AL    2012    4817528.0
      2010    4785570.0
      2011    4801627.0
      2009    4757938.0
      2013    4833722.0
...                 ...
USA   2013  316128839.0
      2009  306771529.0
      2010  309326295.0
      2011  311582564.0
      2012  313873685.0

[1272 rows x 1 columns]

In [62]:
state_pops.loc['USA'].head()

       population
year
1990  249622814.0
1991  252980942.0
1992  256514231.0
1993  259918595.0
1994  263125826.0

#### We can also provide a list to search

In [63]:
state_pops.loc[['AK', 'CA']]

            population
state year
AK    1990    553290.0
      1992    588736.0
      1994    603308.0
      1991    570193.0
      1993    599434.0
      1995    604412.0
      1996    608569.0
      1998    619933.0
      1997    612968.0
      1999    624779.0
      2000    627963.0
      2001    633714.0
      2002    642337.0
      2003    648414.0
      2004    659286.0
      2005    666946.0
      2006    675302.0
      2007    680300.0
      2008    687455.0
      2013    735132.0
      2009    698895.0
      2010    713868.0
      2011    723375.0
      2012    730307.0
CA    2012  37999878.0
      2011  37668681.0
      2010  37333601.0
      2013  38332521.0
      2009  36961229.0
      2007  36250311.0
      2008  36604337.0
      2005  35827943.0
      2006  36021202.0
      2003  35253159.0
      2004  35574576.0
      2001  34479458.0
      2002  34871843.0
      1999  33499204.0
      2000  33987977.0
      1998  32987675.0
      1997  32486010.0
      1996  32018834.0
      1995  31696582.0
      1993  31274928.0
      1994  31484435.0
      1991  30470736.0
      1992  30974659.0
      1990  29959515.0

#### We can also use a range to search but for that we need to sort by index first

In [64]:
state_pops = state_pops.sort_index()

In [65]:
state_pops.loc['NM' : 'TX']

            population
state year
NM    1990   1521574.0
      1991   1555305.0
      1992   1595442.0
      1993   1636453.0
      1994   1682398.0
...                ...
TX    2009  24801761.0
      2010  25245178.0
      2011  25640909.0
      2012  26060796.0
      2013  26448193.0

[312 rows x 1 columns]

## I want the population of Montana from 1992

In [66]:
state_pops_MT = state_pops.loc['MT'].loc[1992]
state_pops_MT

population    825770.0
Name: 1992, dtype: float64

##### Another way of doing this

In [67]:
state_pops.loc['MT', 1992]

population    825770.0
Name: (MT, 1992), dtype: float64

##### Another safer way of doing this is by passing a tuple inside .loc[ ]

In [68]:
state_pops.loc[('MT', 1992)]

population    825770.0
Name: (MT, 1992), dtype: float64

## I want California's population in 2013

In [69]:
state_pops.loc[('CA', 2013)]

population    38332521.0
Name: (CA, 2013), dtype: float64

# Using slice/range

## I want the population of Alaska from 1990 to 1995

In [70]:
state_pops.loc[('AK', 1990) : ('AK', 1995)]

            population
state year
AK    1990    553290.0
      1991    570193.0
      1992    588736.0
      1993    599434.0
      1994    603308.0
      1995    604412.0

## I want the population of Alaska and Alabama from 2011 to 1993

In [71]:
state_pops.loc[('AK', 2011) : ('AL', 1993)]

            population
state year
AK    2011    723375.0
      2012    730307.0
      2013    735132.0
AL    1990   4050055.0
      1991   4099156.0
      1992   4154014.0
      1993   4214202.0

## I want to access the second index column
## df.loc[:, search_term, :]
##### : represents all of the ones before/after

In [73]:
state_pops.loc[:, 1990, :]

        population
state
AK        553290.0
AL       4050055.0
AR       2356586.0
AZ       3684097.0
CA      29959515.0
CO       3307618.0
CT       3291967.0
DC        605321.0
DE        669567.0
FL      13033307.0
GA       6512602.0
HI       1113491.0
IA       2781018.0
ID       1012384.0
IL      11453316.0
IN       5557798.0
KS       2481349.0
KY       3694048.0
LA       4221532.0
MA       6022639.0
MD       4799770.0
ME       1231719.0
MI       9311319.0
MN       4389857.0
MO       5128880.0
MS       2578897.0
MT        800204.0
NC       6664016.0
ND        637685.0
NE       1581660.0
NH       1112384.0
NJ       7762963.0
NM       1521574.0
NV       1220695.0
NY      18020784.0
OH      10864162.0
OK       3148825.0
OR       2860375.0
PA      11903299.0
PR             NaN
RI       1005995.0
SC       3501155.0
SD        697101.0
TN       4894492.0
TX      17056755.0
USA    249622814.0
UT       1731223.0
VA       6216884.0
VT        564798.0
WA       4903043.0
WI       4904562.0
WV       1792548.0
WY        453690.0

## Using the above method we can also do a slice

In [76]:
state_pops.loc[:, [1990, 1992], :]

            population
state year
AK    1990    553290.0
      1992    588736.0
AL    1990   4050055.0
      1992   4154014.0
AR    1990   2356586.0
...                ...
WI    1992   5025398.0
WV    1990   1792548.0
      1992   1806451.0
WY    1990    453690.0
      1992    466251.0

[106 rows x 1 columns]