# Multi-Indexing - sort_index()

In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv('../../../data/titanic.csv')

In [4]:
state_pop = pd.read_csv('../../../data/state_pops.csv')

#### We will first set multi-index for the state population dataset using set_index()

In [6]:
state_pop.set_index(['state', 'year'], inplace=True)

In [8]:
state_pop.head()

            population
state year
AL    2012   4817528.0
      2010   4785570.0
      2011   4801627.0
      2009   4757938.0
      2013   4833722.0

## Now we will use sort_index() on this dataframe which will sort both the columns

In [9]:
state_pop.sort_index()

            population
state year
AK    1990    553290.0
      1991    570193.0
      1992    588736.0
      1993    599434.0
      1994    603308.0
...                ...
WY    2009    559851.0
      2010    564222.0
      2011    567329.0
      2012    576626.0
      2013    582658.0

[1272 rows x 1 columns]

In [10]:
state_pop.sort_index(ascending=False)

            population
state year
WY    2013    582658.0
      2012    576626.0
      2011    567329.0
      2010    564222.0
      2009    559851.0
...                ...
AK    1994    603308.0
      1993    599434.0
      1992    588736.0
      1991    570193.0
      1990    553290.0

[1272 rows x 1 columns]

# using level= we can control the column we want to sort

In [11]:
state_pop.sort_index(ascending=False, level=0)

            population
state year
WY    2013    582658.0
      2012    576626.0
      2011    567329.0
      2010    564222.0
      2009    559851.0
...                ...
AK    1994    603308.0
      1993    599434.0
      1992    588736.0
      1991    570193.0
      1990    553290.0

[1272 rows x 1 columns]

In [12]:
state_pop.sort_index(ascending=False, level=1)

            population
state year
WY    2013    582658.0
WV    2013   1854304.0
WI    2013   5742713.0
WA    2013   6971406.0
VT    2013    626630.0
...                ...
CA    1990  29959515.0
AZ    1990   3684097.0
AR    1990   2356586.0
AL    1990   4050055.0
AK    1990    553290.0

[1272 rows x 1 columns]

# We can do two differnt sorts on two different columns at once

In [15]:
state_pop.sort_index(level = [0,1], ascending=[False,True])

            population
state year
WY    1990    453690.0
      1991    459260.0
      1992    466251.0
      1993    473081.0
      1994    480283.0
...                ...
AK    2009    698895.0
      2010    713868.0
      2011    723375.0
      2012    730307.0
      2013    735132.0

[1272 rows x 1 columns]