# Multi Indexing get_level_values()
### The DataFrame.index.get_level_values() method in pandas extracts a flat vector of label values from a specific level of a multi-level index (MultiIndex). It returns a standard pandas Index object matching the exact length and order of your DataFrame rows

In [1]:
import pandas as pd

In [2]:
state_pops = pd.read_csv('../../../data/state_pops.csv')
state_pops.head()

  state  year  population
0    AL  2012   4817528.0
1    AL  2010   4785570.0
2    AL  2011   4801627.0
3    AL  2009   4757938.0
4    AL  2013   4833722.0

In [4]:
state_pops.set_index(['state', 'year'], inplace=True)

In [5]:
state_pops

             population
state year
AL    2012    4817528.0
      2010    4785570.0
      2011    4801627.0
      2009    4757938.0
      2013    4833722.0
...                 ...
USA   2013  316128839.0
      2009  306771529.0
      2010  309326295.0
      2011  311582564.0
      2012  313873685.0

[1272 rows x 1 columns]

In [24]:
state_pops.index

MultiIndex([( 'AL', 2012),
            ( 'AL', 2010),
            ( 'AL', 2011),
            ( 'AL', 2009),
            ( 'AL', 2013),
            ( 'AL', 2007),
            ( 'AL', 2008),
            ( 'AL', 2005),
            ( 'AL', 2006),
            ( 'AL', 2004),
            ...
            ('USA', 2004),
            ('USA', 2005),
            ('USA', 2006),
            ('USA', 2007),
            ('USA', 2008),
            ('USA', 2013),
            ('USA', 2009),
            ('USA', 2010),
            ('USA', 2011),
            ('USA', 2012)],
           names=['state', 'year'], length=1272)

In [7]:
state_pops.index.levels

FrozenList([['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'USA', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], [1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]])

In [9]:
state_pops.index.get_level_values(0)

Index(['AL', 'AL', 'AL', 'AL', 'AL', 'AL', 'AL', 'AL', 'AL', 'AL',
       ...
       'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA'],
      dtype='object', name='state', length=1272)

In [10]:
state_pops.index.get_level_values(1)

Index([2012, 2010, 2011, 2009, 2013, 2007, 2008, 2005, 2006, 2004,
       ...
       2004, 2005, 2006, 2007, 2008, 2013, 2009, 2010, 2011, 2012],
      dtype='int64', name='year', length=1272)

### We can also access the content inside the get_level_values() list by specifying its position

In [13]:
state_pops.index.get_level_values(0)[20]

'AL'

In [14]:
state_pops.index.get_level_values(1)[900]

np.int64(2002)

In [15]:
state_pops.loc[:, [1990,1992,1994], :]

             population
state year
AL    1990    4050055.0
AK    1990     553290.0
AZ    1990    3684097.0
AR    1990    2356586.0
CA    1990   29959515.0
...                 ...
WV    1994    1820421.0
WI    1994    5133678.0
WY    1994     480283.0
PR    1994          NaN
USA   1994  263125826.0

[159 rows x 1 columns]

### We can also perform some maths to it and pass it as a mask into loc[ ]

In [20]:
even_years = state_pops.index.get_level_values(1) % 2 == 0

state_pops.loc[even_years]

             population
state year
AL    2012    4817528.0
      2010    4785570.0
      2008    4718206.0
      2006    4628981.0
      2004    4530729.0
...                 ...
USA   2004  292805298.0
      2006  298379912.0
      2008  304093966.0
      2010  309326295.0
      2012  313873685.0

[636 rows x 1 columns]

In [22]:
state_pops[state_pops['population'] % 2 ==0]

             population
state year
AL    2012    4817528.0
      2010    4785570.0
      2009    4757938.0
      2013    4833722.0
      2007    4672840.0
...                 ...
USA   1998  275854116.0
      2004  292805298.0
      2006  298379912.0
      2008  304093966.0
      2011  311582564.0

[645 rows x 1 columns]

### We can also access specific character of the index column

In [25]:
state_pops.index.get_level_values(0).str[1]

Index(['L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L',
       ...
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
      dtype='object', name='state', length=1272)

In [26]:
state_pops.index.get_level_values(0).str[0]

Index(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       ...
       'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U'],
      dtype='object', name='state', length=1272)

### We can also create a boolean condition

In [29]:
ends_with_A = state_pops.index.get_level_values(0).str[1] == 'A'
ends_with_A

array([False, False, False, ..., False, False, False])

In [30]:
state_pops[ends_with_A].index.values

array([('CA', 2012), ('CA', 2011), ('CA', 2010), ('CA', 2013),
       ('CA', 2009), ('CA', 2007), ('CA', 2008), ('CA', 2005),
       ('CA', 2006), ('CA', 2003), ('CA', 2004), ('CA', 2001),
       ('CA', 2002), ('CA', 1999), ('CA', 2000), ('CA', 1998),
       ('CA', 1997), ('CA', 1996), ('CA', 1995), ('CA', 1993),
       ('CA', 1994), ('CA', 1991), ('CA', 1992), ('CA', 1990),
       ('GA', 2012), ('GA', 2011), ('GA', 2010), ('GA', 2013),
       ('GA', 2009), ('GA', 2007), ('GA', 2008), ('GA', 2005),
       ('GA', 2006), ('GA', 2003), ('GA', 2004), ('GA', 2001),
       ('GA', 2002), ('GA', 1999), ('GA', 2000), ('GA', 1997),
       ('GA', 1998), ('GA', 1996), ('GA', 1995), ('GA', 1992),
       ('GA', 1993), ('GA', 1994), ('GA', 1991), ('GA', 1990),
       ('IA', 1990), ('IA', 1991), ('IA', 1994), ('IA', 1993),
       ('IA', 1992), ('IA', 1995), ('IA', 1996), ('IA', 1998),
       ('IA', 1997), ('IA', 2000), ('IA', 1999), ('IA', 2002),
       ('IA', 2001), ('IA', 2004), ('IA', 2003), ('IA', 2006),
       ('IA', 2005), ('IA', 2008), ('IA', 2007), ('IA', 2009),
       ('IA', 2013), ('IA', 2010), ('IA', 2011), ('IA', 2012),
       ('LA', 2012), ('LA', 2011), ('LA', 2010), ('LA', 2013),
       ('LA', 2009), ('LA', 2007), ('LA', 2008), ('LA', 2005),
       ('LA', 2006), ('LA', 2003), ('LA', 2004), ('LA', 2001),
       ('LA', 2002), ('LA', 2000), ('LA', 1999), ('LA', 1997),
       ('LA', 1998), ('LA', 1996), ('LA', 1995), ('LA', 1992),
       ('LA', 1993), ('LA', 1994), ('LA', 1991), ('LA', 1990),
       ('MA', 1990), ('MA', 1991), ('MA', 1994), ('MA', 1993),
       ('MA', 1992), ('MA', 1995), ('MA', 1996), ('MA', 1998),
       ('MA', 1997), ('MA', 1999), ('MA', 2000), ('MA', 2001),
       ('MA', 2002), ('MA', 2004), ('MA', 2003), ('MA', 2006),
       ('MA', 2005), ('MA', 2008), ('MA', 2007), ('MA', 2009),
       ('MA', 2013), ('MA', 2010), ('MA', 2011), ('MA', 2012),
       ('PA', 2012), ('PA', 2011), ('PA', 2010), ('PA', 2009),
       ('PA', 2013), ('PA', 2007), ('PA', 2008), ('PA', 2006),
       ('PA', 2005), ('PA', 2003), ('PA', 2004), ('PA', 2002),
       ('PA', 2001), ('PA', 1999), ('PA', 2000), ('PA', 1997),
       ('PA', 1998), ('PA', 1996), ('PA', 1995), ('PA', 1994),
       ('PA', 1992), ('PA', 1993), ('PA', 1991), ('PA', 1990),
       ('VA', 2012), ('VA', 2011), ('VA', 2010), ('VA', 2009),
       ('VA', 2013), ('VA', 2007), ('VA', 2008), ('VA', 2005),
       ('VA', 2006), ('VA', 2003), ('VA', 2004), ('VA', 2002),
       ('VA', 2001), ('VA', 1999), ('VA', 2000), ('VA', 1997),
       ('VA', 1998), ('VA', 1996), ('VA', 1995), ('VA', 1994),
       ('VA', 1992), ('VA', 1993), ('VA', 1991), ('VA', 1990),
       ('WA', 1990), ('WA', 1991), ('WA', 1993), ('WA', 1992),
       ('WA', 1994), ('WA', 1995), ('WA', 1996), ('WA', 1998),
       ('WA', 1997), ('WA', 2000), ('WA', 1999), ('WA', 2001),
       ('WA', 2002), ('WA', 2004), ('WA', 2003), ('WA', 2005),
       ('WA', 2006), ('WA', 2008), ('WA', 2007), ('WA', 2013),
       ('WA', 2009), ('WA', 2010), ('WA', 2011), ('WA', 2012)],
      dtype=object)