# Stack() and Unstack()

In [1]:
import pandas as pd

In [4]:
state_pops = pd.read_csv('../../../data/state_pops.csv')

In [5]:
state_pops.set_index(['state', 'year'], inplace=True)

In [6]:
state_pops.head()

            population
state year
AL    2012   4817528.0
      2010   4785570.0
      2011   4801627.0
      2009   4757938.0
      2013   4833722.0

# unstack()

In [9]:
state_pops.unstack('year').head()

       population                                                              \
year         1990        1991        1992        1993        1994        1995
state
AK       553290.0    570193.0    588736.0    599434.0    603308.0    604412.0
AL      4050055.0   4099156.0   4154014.0   4214202.0   4260229.0   4296800.0
AR      2356586.0   2383144.0   2415984.0   2456303.0   2494019.0   2535399.0
AZ      3684097.0   3788576.0   3915740.0   4065440.0   4245089.0   4432499.0
CA     29959515.0  30470736.0  30974659.0  31274928.0  31484435.0  31696582.0

                                                       ...              \
year         1996        1997        1998        1999  ...        2004
state                                                  ...
AK       608569.0    612968.0    619933.0    624779.0  ...    659286.0
AL      4331103.0   4367935.0   4404701.0   4430141.0  ...   4530729.0
AR      2572109.0   2601091.0   2626289.0   2651860.0  ...   2749686.0
AZ      4586940.0   4736990.0   4883342.0   5023823.0  ...   5652404.0
CA     32018834.0  32486010.0  32987675.0  33499204.0  ...  35574576.0

                                                                               \
year         2005        2006        2007        2008        2009        2010
state
AK       666946.0    675302.0    680300.0    687455.0    698895.0    713868.0
AL      4569805.0   4628981.0   4672840.0   4718206.0   4757938.0   4785570.0
AR      2781097.0   2821761.0   2848650.0   2874554.0   2896843.0   2922280.0
AZ      5839077.0   6029141.0   6167681.0   6280362.0   6343154.0   6408790.0
CA     35827943.0  36021202.0  36250311.0  36604337.0  36961229.0  37333601.0


year         2011        2012        2013
state
AK       723375.0    730307.0    735132.0
AL      4801627.0   4817528.0   4833722.0
AR      2938506.0   2949828.0   2959373.0
AZ      6468796.0   6551149.0   6626624.0
CA     37668681.0  37999878.0  38332521.0

[5 rows x 24 columns]

In [16]:
state_pops.unstack('state').head()

      population                                                          \
state         AK         AL         AR         AZ          CA         CO
year
1990    553290.0  4050055.0  2356586.0  3684097.0  29959515.0  3307618.0
1991    570193.0  4099156.0  2383144.0  3788576.0  30470736.0  3387119.0
1992    588736.0  4154014.0  2415984.0  3915740.0  30974659.0  3495939.0
1993    599434.0  4214202.0  2456303.0  4065440.0  31274928.0  3613734.0
1994    603308.0  4260229.0  2494019.0  4245089.0  31484435.0  3724168.0

                                                  ...                         \
state         CT        DC        DE          FL  ...         TN          TX
year                                              ...
1990   3291967.0  605321.0  669567.0  13033307.0  ...  4894492.0  17056755.0
1991   3302895.0  600870.0  683080.0  13369798.0  ...  4966587.0  17398005.0
1992   3300712.0  597567.0  694927.0  13650553.0  ...  5049742.0  17759738.0
1993   3309175.0  595302.0  706378.0  13927185.0  ...  5137584.0  18161612.0
1994   3316121.0  589240.0  717545.0  14239444.0  ...  5231438.0  18564062.0

                                                                          \
state          USA         UT         VA        VT         WA         WI
year
1990   249622814.0  1731223.0  6216884.0  564798.0  4903043.0  4904562.0
1991   252980942.0  1779780.0  6301217.0  568606.0  5025624.0  4964343.0
1992   256514231.0  1836799.0  6414307.0  572751.0  5160757.0  5025398.0
1993   259918595.0  1898404.0  6509630.0  577748.0  5278842.0  5084889.0
1994   263125826.0  1960446.0  6593139.0  583836.0  5375161.0  5133678.0


state         WV        WY
year
1990   1792548.0  453690.0
1991   1798735.0  459260.0
1992   1806451.0  466251.0
1993   1817539.0  473081.0
1994   1820421.0  480283.0

[5 rows x 53 columns]

# stack()

In [15]:
unstacked_state_pops = state_pops.unstack(level = 'state').head()

In [17]:
unstacked_state_pops.stack()

/var/folders/js/d6m95rq92m76bb_bzchbyb1c0000gn/T/ipykernel_39359/3797319550.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  unstacked_state_pops.stack()

            population
year state
1990 AK       553290.0
     AL      4050055.0
     AR      2356586.0
     AZ      3684097.0
     CA     29959515.0
...                ...
1994 VT       583836.0
     WA      5375161.0
     WI      5133678.0
     WV      1820421.0
     WY       480283.0

[260 rows x 1 columns]