# Replacing Values

In [1]:
import pandas as pd 

titanic = pd.read_csv('../../data/titanic.csv')
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

##### Replace 'female' with 'f' in the 'sex' columns

In [5]:
titanic['sex'].replace('female', 'F')

0          F
1       male
2          F
3       male
4          F
        ...
1304       F
1305       F
1306    male
1307    male
1308    male
Name: sex, Length: 1309, dtype: object

##### Replace both 'Male' and 'Female' with their first letters in the sex column

In [7]:
titanic['sex'].replace(['female', 'male'], ['F', 'M'], inplace=True)

In [8]:
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",F,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",M,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",F,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",M,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",F,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

## If you want to repace something with NONE then you have to wrap NONE In square brackets like a list = [None]

#### Replace the '?' in the age column with None

In [11]:
titanic['age'].tail()

1304    14.5
1305       ?
1306    26.5
1307      27
1308      29
Name: age, dtype: object

In [13]:
titanic['age'].replace(['?'], [None])

0           29
1       0.9167
2            2
3           30
4           25
         ...
1304      14.5
1305      None
1306      26.5
1307        27
1308        29
Name: age, Length: 1309, dtype: object

In [16]:
titanic['age'].replace(['?'], [None], inplace=True)

In [21]:
titanic['age'].value_counts(dropna=False)

age
None      263
24         47
22         43
21         41
30         40
         ...
66          1
0.6667      1
76          1
67          1
26.5        1
Name: count, Length: 99, dtype: int64

In [22]:
titanic['age'].tail()

1304    14.5
1305    None
1306    26.5
1307      27
1308      29
Name: age, dtype: object