# Comparing Dates

In [11]:
import pandas as pd

ufo = pd.read_csv('../../data/nuforc_reports.csv 19-47-12-819.csv')

In [12]:
ufo.head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,2019-12-12T18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,2019-03-22T18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
2,I woke up late in the afternoon 3:30-4pm. I we...,NaN,NaN,NaN,NaN,NaN,Occurred : 4/1/2019 15:45 (Entered as : April...,http://www.nuforc.org/webreports/145/S145556.html,I woke up late in the afternoon 3:30-4pm. I w...,NaN,NaN,NaN
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17T02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
4,"In Peoria Arizona, I saw a cigar shaped craft ...",Peoria,NY,2009-03-15T18:00:00,cigar,2 minutes,Occurred : 3/15/2009 18:00 (Entered as : 03/1...,http://www.nuforc.org/webreports/145/S145723.html,"In Peoria, Arizona, I saw a cigar shaped craft...",2019-04-18T00:00:00,NaN,NaN

In [13]:
ufo['date_time'] = pd.to_datetime(ufo['date_time'])
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88125 entries, 0 to 88124
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   summary         88095 non-null  object
 1   city            87888 non-null  object
 2   state           82890 non-null  object
 3   date_time       86938 non-null  datetime64[ns]
 4   shape           85627 non-null  object
 5   duration        84951 non-null  object
 6   stats           88088 non-null  object
 7   report_link     88125 non-null  object
 8   text            88070 non-null  object
 9   posted          86938 non-null  object
 10  city_latitude   72013 non-null  float64
 11  city_longitude  72013 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 8.1+ MB

In [14]:
ufo['date_time'].dt.year

0        2019.0
1        2019.0
2           NaN
3        2019.0
4        2009.0
          ...
88120    2019.0
88121    2019.0
88122    2019.0
88123    2019.0
88124    2019.0
Name: date_time, Length: 88125, dtype: float64

### We can use comparison operators to create conditions

In [15]:
ufo['date_time'] > '1980'

0         True
1         True
2        False
3         True
4         True
         ...
88120     True
88121     True
88122     True
88123     True
88124     True
Name: date_time, Length: 88125, dtype: bool

In [16]:
ufo[ufo['date_time'] > '1980'].head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,2019-12-12 18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,2019-03-22 18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17 02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
4,"In Peoria Arizona, I saw a cigar shaped craft ...",Peoria,NY,2009-03-15 18:00:00,cigar,2 minutes,Occurred : 3/15/2009 18:00 (Entered as : 03/1...,http://www.nuforc.org/webreports/145/S145723.html,"In Peoria, Arizona, I saw a cigar shaped craft...",2019-04-18T00:00:00,NaN,NaN
5,"The object has flashing lights that are green,...",Kirbyville,TX,2019-04-02 20:25:00,disk,15 minutes,Occurred : 4/2/2019 20:25 (Entered as : 04/02...,http://www.nuforc.org/webreports/145/S145476.html,"The object has flashing lights that are green,...",2019-04-08T00:00:00,30.677200,-94.005200

In [19]:
ufo[ufo['date_time'].dt.hour == 2.0].head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17 02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
14,Bright Circle of Light followed me from Oskalo...,Centerville,IA,1999-08-15 02:30:00,circle,1 hour,Occurred : 8/15/1999 02:30 (Entered as : 08/1...,http://www.nuforc.org/webreports/146/S146702.html,Bright Circle of Light followed me from Oskalo...,2019-06-20T00:00:00,40.707400,-92.921300
148,Strange Vibrations...,Indianola,IA,1992-04-30 02:00:00,unknown,5 Minutes,Occurred : 4/30/1992 02:00 (Entered as : 04/3...,http://www.nuforc.org/webreports/050/S50488.html,Strange Vibrations... When I was young; about ...,2006-05-15T00:00:00,41.306800,-93.582600
153,"red ball ufo following small plane in tracy, c...",Tracy,CA,1993-06-15 02:00:00,light,3 minutes,Occurred : 6/15/1993 02:00 (Entered as : 1992...,http://www.nuforc.org/webreports/049/S49607.html,"red ball ufo following small plane in tracy, c...",2006-05-15T00:00:00,37.705000,-121.457715
181,Silver disk flies through sky making zigzaggin...,Beaverton,OR,2015-04-16 02:30:00,disk,5-8 minutes,Occurred : 4/16/2015 02:30 (Entered as : 4/16...,http://www.nuforc.org/webreports/145/S145230.html,Silver disk flies through sky making zigzaggin...,2019-03-21T00:00:00,45.483560,-122.837435

In [25]:
ufo[ufo['date_time'].between('2000', '2001')].sort_values('date_time').head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
13200,"It's a plane, it's a star, NO it's a UFO!",Clovis,CA,2000-01-01 05:00:00,light,1 min,Occurred : 1/1/2000 05:00 (Entered as : 01/01...,http://www.nuforc.org/webreports/055/S55146.html,"It's a plane, it's a star, NO it's a UFO! It w...",2007-02-24T00:00:00,36.863901,-119.652136
1329,Diamond Shape taking samples from Rock River,Rockford,IL,2000-01-01 17:00:00,diamond,5 minutes,Occurred : 1/1/2000 17:00 (Entered as : 01/20...,http://www.nuforc.org/webreports/146/S146614.html,Diamond Shape taking samples from Rock River W...,2019-06-07T00:00:00,42.277381,-89.044778
4459,Triangular shaped object flying very low to th...,Patoka,IL,2000-01-01 21:00:00,triangle,5 minutes,Occurred : 1/1/2000 21:00 (Entered as : 1/200...,http://www.nuforc.org/webreports/063/S63101.html,Triangular shaped object flying very low to th...,2008-06-12T00:00:00,38.758100,-89.101900
312,Yellow egg shape craft displays of technolegy,Erath,LA,2000-01-01 23:00:00,egg,2:00,Occurred : 1/1/2000 23:00 (Entered as : 01/01...,http://www.nuforc.org/webreports/050/S50046.html,Yellow egg shape craft displays of technolegy ...,2006-05-15T00:00:00,29.912600,-92.042000
16722,A rectangle shape object like a cigar box (may...,Jacksonville,FL,2000-01-02 00:00:00,rectangle,2hrs,Occurred : 1/2/2000 00:00 (Entered as : 01/02...,http://www.nuforc.org/webreports/067/S67451.html,A rectangle shape object like a cigar box (may...,2009-01-10T00:00:00,30.266905,-81.616373