# fillna()
#### Helps to replace NaN values with some other values

In [1]:
import pandas as pd

games = pd.read_csv('../../../data/game_stats.csv')

In [3]:
games

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN         NaN     NaN      NaN       NaN

#### We will change all the NaN values with 0

In [4]:
games.fillna(0)

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie           0    10.0      0.0       2.0
2       stu  euroleague     0.0      0.0       0.0
3   jackson         aba     9.0      0.0       2.0
4  timothee           0     8.0      0.0       0.0
5     steph         nba    49.0      8.0      10.0
6         0           0     0.0      0.0       0.0

#### We will target a specific column to replace NaN values

In [5]:
games['league'].fillna('Batman')

0           nba
1        Batman
2    euroleague
3           aba
4        Batman
5           nba
6        Batman
Name: league, dtype: object

#### We can target multiple columns now to replace NaN values using a dictionary

In [6]:
games.fillna({'league' : 'Superman', 'points' : 0, 'assists' : 5})

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie    Superman    10.0      5.0       2.0
2       stu  euroleague     0.0      5.0       NaN
3   jackson         aba     9.0      5.0       2.0
4  timothee    Superman     8.0      5.0       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN    Superman     0.0      5.0       NaN

### We can use fillna() to fill NaN values with values from another column of our choice

In [7]:
import pandas as pd

sales = pd.read_csv('../../../data/sales.csv')
sales

   rating  shipping_zip  billing_zip
0     5.0           NaN      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0           NaN      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0

In [9]:
sales['shipping_zip'].fillna(sales['billing_zip'], inplace=True)

/var/folders/js/d6m95rq92m76bb_bzchbyb1c0000gn/T/ipykernel_52591/1556474809.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales['shipping_zip'].fillna(sales['billing_zip'], inplace=True)

In [10]:
sales

   rating  shipping_zip  billing_zip
0     5.0       81220.0      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0       92660.0      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0