# contains()
### The str.contains() method in pandas tests whether a specific substring or regular expression pattern exists within the text elements of a Series or Index

In [1]:
import pandas as pd

In [2]:
ufo = pd.read_csv('../../../data/nuforc_reports.csv 19-47-12-819.csv')

In [4]:
ufo.head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,2019-12-12T18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,2019-03-22T18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
2,I woke up late in the afternoon 3:30-4pm. I we...,NaN,NaN,NaN,NaN,NaN,Occurred : 4/1/2019 15:45 (Entered as : April...,http://www.nuforc.org/webreports/145/S145556.html,I woke up late in the afternoon 3:30-4pm. I w...,NaN,NaN,NaN
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17T02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
4,"In Peoria Arizona, I saw a cigar shaped craft ...",Peoria,NY,2009-03-15T18:00:00,cigar,2 minutes,Occurred : 3/15/2009 18:00 (Entered as : 03/1...,http://www.nuforc.org/webreports/145/S145723.html,"In Peoria, Arizona, I saw a cigar shaped craft...",2019-04-18T00:00:00,NaN,NaN

### Using str.contains('search_term') we can search if a particular word is present or not in a column
### The resultant is almost a boolean series since there NaN is also preserved along with True/False

In [3]:
ufo['duration'].str.contains('hour')

0        False
1        False
2          NaN
3        False
4        False
         ...
88120    False
88121    False
88122    False
88123    False
88124    False
Name: duration, Length: 88125, dtype: object

### The resultant is almost a boolean series

In [5]:
ufo['city'].str.contains('Ottawa')

0        False
1        False
2          NaN
3         True
4        False
         ...
88120    False
88121    False
88122    False
88123    False
88124    False
Name: city, Length: 88125, dtype: object

## If we try to enclose this boolean series into a dataframe then it will throw an error since there are NaN present so we need to pass na=False

In [8]:
ufo[ufo['duration'].str.contains('hour', na=False)]

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
10,Metal orb of wires that was seen through a tel...,Brookville,IN,2019-06-18T21:00:00,sphere,1 hour,Occurred : 6/18/2019 21:00 (Entered as : 6/18...,http://www.nuforc.org/webreports/146/S146900.html,Metal orb of wires that was seen through a tel...,2019-06-20T00:00:00,39.404700,-84.973600
14,Bright Circle of Light followed me from Oskalo...,Centerville,IA,1999-08-15T02:30:00,circle,1 hour,Occurred : 8/15/1999 02:30 (Entered as : 08/1...,http://www.nuforc.org/webreports/146/S146702.html,Bright Circle of Light followed me from Oskalo...,2019-06-20T00:00:00,40.707400,-92.921300
36,"Looked like airplanes without windows, wings,...",Morehouse,MO,NaN,cylinder,hours,Occurred : 7/15/1947 21:00 (Entered as : 07/?...,http://www.nuforc.org/webreports/049/S49557.html,"Looked like airplanes without windows, wings, ...",NaN,36.849900,-89.677200
37,01/20/51 Palm Springs CA light hou...,Palm Springs,CA,NaN,cigar,one and a half hours,Occurred : 1/20/1951 04:30 (Entered as : 01/2...,http://www.nuforc.org/webreports/050/S50060.html,01/20/51 Palm Springs CA light hou...,NaN,33.800165,-116.535373
40,"5/16/1958/ 1500 hours/ just getting dark,mount...",Cincinnati,OH,NaN,diamond,24 hours,Occurred : 5/16/1958 (Entered as : 05/16/58)...,http://www.nuforc.org/webreports/049/S49850.html,"5/16/1958/ 1500 hours/ just getting dark,mount...",NaN,39.174503,-84.481363
...,...,...,...,...,...,...,...,...,...,...,...,...
88013,Unidentified flying object seen multiple night...,New port richey,FL,2019-09-27T21:00:00,unknown,1 hour,Occurred : 9/27/2019 21:00 (Entered as : 09/2...,http://www.nuforc.org/webreports/149/S149318.html,Unidentified flying object seen multiple night...,2019-10-04T00:00:00,28.242700,-82.677239
88018,On balcony enjoying a beautiful night by the b...,New York,NY,2019-09-27T22:00:00,light,1 hour,Occurred : 9/27/2019 22:00 (Entered as : 09/2...,http://www.nuforc.org/webreports/149/S149283.html,On balcony enjoying a beautiful night by the b...,2019-10-04T00:00:00,40.744307,-73.987724
88064,Unidentified object moving very slowly across ...,Pt. St. Lucie,FL,2019-09-29T17:00:00,circle,1.5 hours,Occurred : 9/29/2019 17:00 (Entered as : 09/2...,http://www.nuforc.org/webreports/149/S149338.html,Unidentified object moving very slowly across ...,2019-10-04T00:00:00,NaN,NaN
88065,White circular object above Ft Pierce,Fort Pierce,FL,2019-09-29T17:20:00,circle,1:30 hours,Occurred : 9/29/2019 17:20 (Entered as : 9/29...,http://www.nuforc.org/webreports/149/S149345.html,White circular object above Ft Pierce Very lar...,2019-10-04T00:00:00,NaN,NaN
88073,Lights in Texas sky,Slocum,TX,2019-09-29T23:00:00,light,>1 hour,Occurred : 9/29/2019 23:00 (Entered as : 09/2...,http://www.nuforc.org/webreports/149/S149344.html,Lights in Texas sky Saw a strange bright light...,2019-10-04T00:00:00,NaN,NaN

In [11]:
ufo[ufo['duration'].str.contains('day|week|month', na=False)]

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
107,7 large yellow lights with red center estimat...,Griffin,GA,1984-03-15T20:00:00,circle,3 months,Occurred : 3/15/1984 20:00 (Entered as : marc...,http://www.nuforc.org/webreports/050/S50375.html,7 large yellow lights with red center estimat...,2006-05-15T00:00:00,33.248869,-84.249217
116,Saw one large ship during the day around noon ...,Knoxville,TN,1986-04-04T23:00:00,rectangle,week,Occurred : 4/4/1986 23:00 (Entered as : 03150...,http://www.nuforc.org/webreports/049/S49786.html,Saw one large ship during the day around noon ...,2006-05-15T00:00:00,35.961561,-83.980115
286,film makers in hollywood where talking of film...,Arizona,AZ,1997-07-07T00:00:00,triangle,all months,Occurred : 7/7/1997 (Entered as : 7 7 1997) ...,http://www.nuforc.org/webreports/049/S49553.html,film makers in hollywood where talking of film...,2006-05-15T00:00:00,NaN,NaN
290,End of the Century UFO,Cebu City (Philippines),NaN,1998-03-01T20:00:00,other,1 to 2 months,Occurred : 3/1/1998 20:00 (Entered as : 03/01...,http://www.nuforc.org/webreports/050/S50203.html,End of the Century UFO First of all I'd like t...,2006-05-15T00:00:00,NaN,NaN
1355,A white ball of light made several appearances...,Genoa,IL,2007-01-25T22:00:00,sphere,5 months,Occurred : 1/25/2007 22:00 (Entered as : 01/2...,http://www.nuforc.org/webreports/146/S146567.html,A white ball of light made several appearances...,2019-06-07T00:00:00,42.108600,-88.686000
...,...,...,...,...,...,...,...,...,...,...,...,...
84021,The Beings and Craft of Taos County. ((NUFORC...,Taos,NM,2019-09-01T10:00:00,other,2 days,Occurred : 9/1/2019 10:00 (Entered as : 09/01...,http://www.nuforc.org/webreports/148/S148913.html,The Beings and Craft of Taos County. ((NUFORC ...,2019-09-19T00:00:00,36.414600,-105.522200
84983,In 1967 I am a little kid now. I am sleeping I...,Saugas,CA,NaN,NaN,3 days,Occurred : 6/30/1967 04:00 Reported: 12/19/201...,http://www.nuforc.org/webreports/144/S144137.html,In 1967 I am a little kid now. I am sleeping ...,NaN,NaN,NaN
85717,There was a big bright colored triangle object...,Houston,BC,2019-11-25T03:30:00,triangle,Till daylight,Occurred : 11/25/2019 03:30 (Entered as : 11/...,http://www.nuforc.org/webreports/151/S151095.html,There was a big bright colored triangle object...,2019-12-01T00:00:00,54.400000,-126.650000
86210,2 flying diamonds; red and gold lights; creaki...,Dallas,TX,2019-10-11T01:44:00,diamond,2 days,Occurred : 10/11/2019 01:44 (Entered as : 10/...,http://www.nuforc.org/webreports/150/S150378.html,2 flying diamonds; red and gold lights; creaki...,2019-12-01T00:00:00,32.835168,-96.808118
87707,Lights seen from the night sky 1st night-flick...,Haiku,HI,2019-11-25T00:00:00,light,4 days,Occurred : 11/25/2019 Reported: 11/29/2019 7:...,http://www.nuforc.org/webreports/151/S151166.html,Lights seen from the night sky 1st night-flick...,2019-12-01T00:00:00,20.858800,-156.140500