# split() - split('/')

In [1]:
import pandas as pd

In [3]:
titanic = pd.read_csv('../../../data/titanic.csv')
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

# We will perform split() on 'home.dest' column

In [4]:
titanic['home.dest'].str.split('/')

0                           [St Louis, MO]
1       [Montreal, PQ ,  Chesterville, ON]
2       [Montreal, PQ ,  Chesterville, ON]
3       [Montreal, PQ ,  Chesterville, ON]
4       [Montreal, PQ ,  Chesterville, ON]
                       ...
1304                                   [?]
1305                                   [?]
1306                                   [?]
1307                                   [?]
1308                                   [?]
Name: home.dest, Length: 1309, dtype: object

# Using expand=True we can get a dataframe

In [5]:
titanic['home.dest'].str.split('/', expand=True)

                  0                  1     2
0      St Louis, MO               None  None
1     Montreal, PQ    Chesterville, ON  None
2     Montreal, PQ    Chesterville, ON  None
3     Montreal, PQ    Chesterville, ON  None
4     Montreal, PQ    Chesterville, ON  None
...             ...                ...   ...
1304              ?               None  None
1305              ?               None  None
1306              ?               None  None
1307              ?               None  None
1308              ?               None  None

[1309 rows x 3 columns]

In [7]:
titanic['home'] = titanic['home.dest'].str.split('/', expand=True)[0]

In [10]:
titanic['destination'] = titanic['home.dest'].str.split('/', expand=True)[1]

In [11]:
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,home,destination
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO","St Louis, MO",None
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON","Montreal, PQ","Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON","Montreal, PQ","Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON","Montreal, PQ","Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON","Montreal, PQ","Chesterville, ON"

In [12]:
titanic['home'].value_counts()

home
?                                564
New York, NY                      64
Cornwall                          19
London                            14
London                            13
                                ...
Chelsea, London                    1
Harrow-on-the-Hill, Middlesex      1
Copenhagen, Denmark                1
Frankfort, KY                      1
Antwerp, Belgium                   1
Name: count, Length: 339, dtype: int64

In [13]:
titanic['destination'].value_counts()

destination
Akron, OH          11
Montreal, PQ        9
New York, NY        9
Detroit, MI         6
Cooperstown, NY     5
                   ..
Rochester, NY       1
 New York, NY       1
Pennsylvania        1
Toledo, OH          1
Stanton, OH         1
Name: count, Length: 77, dtype: int64

# We can control the number of splits via the parameter n=

In [14]:
titanic['home.dest'].str.split('/', expand=True, n=1)

                  0                  1
0      St Louis, MO               None
1     Montreal, PQ    Chesterville, ON
2     Montreal, PQ    Chesterville, ON
3     Montreal, PQ    Chesterville, ON
4     Montreal, PQ    Chesterville, ON
...             ...                ...
1304              ?               None
1305              ?               None
1306              ?               None
1307              ?               None
1308              ?               None

[1309 rows x 2 columns]