In [1]:
import pandas as pd

In [2]:
livestock = pd.DataFrame(
    [['pasture', 9], ['stable', 3], ['coop', 34]],
    columns=['location', 'qty'],
    index=['alpaca', 'horse', 'chicken']
)
weights = pd.DataFrame(
    [[4,10], [900, 2000], [1.2, 4], [110, 150]],
    columns=['min_weight', 'max_weight'],
    index=['chicken', 'horse', 'duck', 'alpaca']
)

In [6]:
pd.concat([livestock, weights])

        location   qty  min_weight  max_weight
alpaca   pasture   9.0         NaN         NaN
horse     stable   3.0         NaN         NaN
chicken     coop  34.0         NaN         NaN
chicken      NaN   NaN         4.0        10.0
horse        NaN   NaN       900.0      2000.0
duck         NaN   NaN         1.2         4.0
alpaca       NaN   NaN       110.0       150.0

In [7]:
pd.concat([livestock, weights], axis=1)

        location   qty  min_weight  max_weight
alpaca   pasture   9.0       110.0         150
horse     stable   3.0       900.0        2000
chicken     coop  34.0         4.0          10
duck         NaN   NaN         1.2           4

In [8]:
pd.concat([livestock, weights], axis=1 , join='inner')

        location  qty  min_weight  max_weight
alpaca   pasture    9       110.0         150
horse     stable    3       900.0        2000
chicken     coop   34         4.0          10