# Concatenating Dataframes

In [11]:
import pandas as pd

In [12]:
harvest_21 = pd.DataFrame(
    [['potatoes', 900], ['garlic', 1350], ['onions', 875]],
    columns=['crop', 'qty']
)

harvest_22 = pd.DataFrame(
    [['garlic', 1600], ['spinach', 560], ['turnips', 999], ['onions', 1000]],
    columns=['crop', 'qty']
)

In [13]:
pd.concat([harvest_21, harvest_22], keys=[2021,2022])

            crop   qty
2021 0  potatoes   900
     1    garlic  1350
     2    onions   875
2022 0    garlic  1600
     1   spinach   560
     2   turnips   999
     3    onions  1000

In [14]:
harvest_23 = pd.DataFrame(
    [['potatoes', 900, 500], ['garlic', 1350, 1200], ['onions', 875, 950]],
    columns=['crop', 'qty', 'profit']
)

In [15]:
harvest_23

       crop   qty  profit
0  potatoes   900     500
1    garlic  1350    1200
2    onions   875     950

## Outer Join

In [17]:
pd.concat([harvest_21, harvest_22, harvest_23])

       crop   qty  profit
0  potatoes   900     NaN
1    garlic  1350     NaN
2    onions   875     NaN
0    garlic  1600     NaN
1   spinach   560     NaN
2   turnips   999     NaN
3    onions  1000     NaN
0  potatoes   900   500.0
1    garlic  1350  1200.0
2    onions   875   950.0

## Inner Join

In [18]:
pd.concat([harvest_21, harvest_22, harvest_23], join='inner')

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
0    garlic  1600
1   spinach   560
2   turnips   999
3    onions  1000
0  potatoes   900
1    garlic  1350
2    onions   875