# DataFrame merge() method
# pandas.DataFrame.merge()
#### df.merge() function in Pandas combines two DataFrames using database-style, SQL-like joins based on common columns or indexes

In [1]:
import pandas as pd

In [2]:
teams = pd.DataFrame(
    [
        ["Suns", "Phoenix", 20, 4],
        ["Mavericks", "Dallas", 11,12],
        ["Rockets", "Houston", 7, 16],
        ["Nuggets", "Denver", 11, 12]
    ],
    columns=["team", "city", "wins", "losses"]
)

cities = pd.DataFrame(
    [
        ["Houston", "Texas", 2310000],
        ["Phoenix", "Arizona", 1630000],
        ["San Diego", "California", 1410000],
        ["Dallas", "Texas", 1310000]
    ],
    columns=["city", "state", "population"]
)

# Inner Join (Default)

In [3]:
teams.merge(cities)

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

# on= parameter helps us to define the field that we want to use for joining

In [5]:
teams.merge(cities, on='city')

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

# how= parameter helps us to define the JOIN type. By default it is INNER Join

# Left Join

In [7]:
teams.merge(cities, how='left')

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona   1630000.0
1  Mavericks   Dallas    11      12    Texas   1310000.0
2    Rockets  Houston     7      16    Texas   2310000.0
3    Nuggets   Denver    11      12      NaN         NaN

# Right Join

In [8]:
teams.merge(cities, how='right')

        team       city  wins  losses       state  population
0    Rockets    Houston   7.0    16.0       Texas     2310000
1       Suns    Phoenix  20.0     4.0     Arizona     1630000
2        NaN  San Diego   NaN     NaN  California     1410000
3  Mavericks     Dallas  11.0    12.0       Texas     1310000

# Outer Join

In [9]:
teams.merge(cities, how='outer')

        team       city  wins  losses       state  population
0  Mavericks     Dallas  11.0    12.0       Texas   1310000.0
1    Nuggets     Denver  11.0    12.0         NaN         NaN
2    Rockets    Houston   7.0    16.0       Texas   2310000.0
3       Suns    Phoenix  20.0     4.0     Arizona   1630000.0
4        NaN  San Diego   NaN     NaN  California   1410000.0