# Casting Types with astype()

In [1]:
import pandas as pd

titanic = pd.read_csv('../../data/titanic.csv')
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [2]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1309 non-null   object
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: int64(4), object(10)
memory usage: 143.3+ KB

## We will try to convert the 'age' column from Object to Float

In [5]:
titanic[titanic['age'] == '?']

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
15,1,0,"Baumann, Mr. John D",male,?,0,0,PC 17318,25.925,?,S,?,?,"New York, NY"
37,1,1,"Bradley, Mr. George ('George Arthur Brayton')",male,?,0,0,111427,26.55,?,S,9,?,"Los Angeles, CA"
40,1,0,"Brewe, Dr. Arthur Jackson",male,?,0,0,112379,39.6,?,C,?,?,"Philadelphia, PA"
46,1,0,"Cairns, Mr. Alexander",male,?,0,0,113798,31,?,S,?,?,?
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,?,0,0,17770,27.7208,?,C,5,?,"New York, NY"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,3,0,"Williams, Mr. Howard Hugh 'Harry'",male,?,0,0,A/5 2466,8.05,?,S,?,?,?
1297,3,0,"Wiseman, Mr. Phillippe",male,?,0,0,A/4. 34244,7.25,?,S,?,?,?
1302,3,0,"Yousif, Mr. Wazli",male,?,0,0,2647,7.225,?,C,?,?,?
1303,3,0,"Yousseff, Mr. Gerious",male,?,0,0,2627,14.4583,?,C,?,?,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?

#### We will first replace the '?' in the age column with None

In [7]:
titanic['age'].replace(['?'], [None], inplace=True)

#### Now first we will create a duplicate column of age but with float type

In [14]:
titanic['age_converted'] = titanic['age'].astype(float)

In [15]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pclass         1309 non-null   int64
 1   survived       1309 non-null   int64
 2   name           1309 non-null   object
 3   sex            1309 non-null   object
 4   age            1046 non-null   object
 5   sibsp          1309 non-null   int64
 6   parch          1309 non-null   int64
 7   ticket         1309 non-null   object
 8   fare           1309 non-null   object
 9   cabin          1309 non-null   object
 10  embarked       1309 non-null   object
 11  boat           1309 non-null   object
 12  body           1309 non-null   object
 13  home.dest      1309 non-null   object
 14  age_converted  1046 non-null   float64
dtypes: float64(1), int64(4), object(10)
memory usage: 153.5+ KB

#### Now we will convert the original age column to float

In [17]:
titanic['age'] = titanic['age'].astype('float')

##### Now we can drop the 'age_converted' column since it is of no use

In [19]:
titanic.drop('age_converted', axis = 1)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.875,?,S,?,?,?