In [4]:
import pandas as pd

In [5]:
# Using pandas read_csv method
df = pd.read_csv('./data/states.csv')

In [17]:
# Using head() method gets you the first five rows sample view
first_5 = df.head()
first_5

        State  Abbrev Code
0     Alabama    Ala.   AL
1      Alaska  Alaska   AK
2     Arizona   Ariz.   AZ
3    Arkansas    Ark.   AR
4  California  Calif.   CA

In [18]:
# Using tail() method gets you the last five rows
last_5 = df.tail()
last_5

            State Abbrev Code
46       Virginia    Va.   VA
47     Washington  Wash.   WA
48  West Virginia  W.Va.   WV
49      Wisconsin   Wis.   WI
50        Wyoming   Wyo.   WY

In [21]:
# We can also control how many rows can be displayed via head
df.head(8)

         State  Abbrev Code
0      Alabama    Ala.   AL
1       Alaska  Alaska   AK
2      Arizona   Ariz.   AZ
3     Arkansas    Ark.   AR
4   California  Calif.   CA
5     Colorado   Colo.   CO
6  Connecticut   Conn.   CT
7     Delaware    Del.   DE

In [22]:
# We can also control how many rows can be displayed via tail
df.tail(8)

            State Abbrev Code
43          Texas   Tex.   TX
44           Utah   Utah   UT
45        Vermont    Vt.   VT
46       Virginia    Va.   VA
47     Washington  Wash.   WA
48  West Virginia  W.Va.   WV
49      Wisconsin   Wis.   WI
50        Wyoming   Wyo.   WY

In [7]:
# To check the data TYPE we use TYPE
type(df)

pandas.core.frame.DataFrame

In [9]:
# To get he complete column names
df.columns

Index(['State', 'Abbrev', 'Code'], dtype='object')

In [10]:
# To get the count on the number of rows in the dataframe/table we use LEN
len(df)

51

In [11]:
# To get the details on both the Number of Rows and Number of Columns we use SHAPE
df.shape

(51, 3)

In [12]:
# To get the SIZE = ROWS * COLUMNS 
df.size

153

In [13]:
# We can configure the minimum number of rows that would be rendered by pandas
pd.options.display.min_rows = 100

In [24]:
# We can get the info of each column in the dataframe (non-null count, column/data type, etc.)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   51 non-null     object
 1   Abbrev  51 non-null     object
 2   Code    51 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [25]:
# We can also see just the DTYPES of the columns
df.dtypes

State     object
Abbrev    object
Code      object
dtype: object